// Copyright (c) 2026 RoryGlenn and commitment-issues contributors
// SPDX-License-Identifier: MIT

// Shared hook-wiring constants and helpers so init, doctor, and the hooks
// themselves all agree on how a consuming project invokes this tool. Hooks are
// plain `.git/hooks` files (git's default location — no core.hooksPath, no
// hook manager) whose bodies run the published `commitment-issues` bin from
// node_modules/.bin, so consumers never vendor scripts or reference
// node_modules paths.
import fs from "node:fs";
import path from "node:path";
import { run } from "./process.mjs";

export const BIN = "commitment-issues";

// Hook name → bin subcommand it runs.
export const HOOK_SUBCOMMANDS = {
  "pre-commit": "precommit",
  "pre-push": "prepush",
  "commit-msg": "commit-msg",
};

export const HOOK_NAMES = Object.keys(HOOK_SUBCOMMANDS);
export const ALWAYS_HOOK_NAMES = ["pre-commit", "pre-push"];

/**
 * Hooks that should be active for a sanitized project configuration.
 * Commit-message linting is the only optional hook and requires an explicit
 * `enabled: true`; uninstall still uses HOOK_NAMES to find every artifact this
 * package may own.
 * @param {object} config - Sanitized precommitChecks configuration.
 * @returns {string[]} Active hook names.
 */
export function hookNamesForConfig(config) {
  return config?.commitMessage?.enabled === true
    ? [...ALWAYS_HOOK_NAMES, "commit-msg"]
    : [...ALWAYS_HOOK_NAMES];
}

/**
 * The bin invocation a hook must contain to count as wired.
 * @param {string} name - Hook name (e.g. "pre-commit").
 * @returns {string} e.g. "commitment-issues precommit".
 */
export function hookCommand(name) {
  const command = `${BIN} ${HOOK_SUBCOMMANDS[name]}`;
  // Git supplies the message file as $1. Keep it quoted in both generated and
  // suggested custom-hook wiring so repositories with unusual paths are safe.
  return name === "commit-msg" ? `${command} "$1"` : command;
}

/**
 * The invocation users should place in a hook. Pre-push must forward Git's
 * remote name and URL so first-push base selection can stay remote-specific.
 * @param {string} name - Hook name (e.g. "pre-commit").
 * @returns {string} Shell invocation for the hook.
 */
export function hookInvocation(name) {
  return name === "pre-push" ? `${hookCommand(name)} "$@"` : hookCommand(name);
}

/**
 * The full generated hook body. POSIX sh (Git for Windows runs hooks through
 * its bundled sh, so this works on every supported platform). The body:
 * - honors COMMITMENT_ISSUES=0 (and HUSKY=0 for pre-3.0 CI recipes) as a skip;
 * - puts node_modules/.bin on PATH (git runs hooks from the repo root);
 * - forwards pre-push's remote name/URL arguments to base selection;
 * - self-neutralizes when the bin is gone (uninstalling the package must never
 *   break commits or pushes).
 * @param {string} name - Hook name (e.g. "pre-commit" or "commit-msg").
 * @returns {string} Hook file contents.
 */
function generatedHookBody(name, { forwardPrePushArgs = true } = {}) {
  const invocation =
    name === "pre-push" && forwardPrePushArgs
      ? hookInvocation(name)
      : hookCommand(name);
  return `#!/bin/sh
# Installed by commitment-issues. Recreate anytime with: ${BIN} doctor
if [ "$COMMITMENT_ISSUES" = "0" ] || [ "$HUSKY" = "0" ]; then
  exit 0
fi
export PATH="node_modules/.bin:$PATH"
if ! command -v ${BIN} >/dev/null 2>&1; then
  echo "${BIN}: command not found; skipping ${name} checks." >&2
  exit 0
fi
${invocation}
`;
}

export function hookBody(name) {
  return generatedHookBody(name);
}

// The pre-push body generated by 3.0-3.2 did not forward Git's remote
// arguments. Its exact content is safe to refresh during an upgrade; anything
// with even one user-authored change remains a custom hook and is never
// overwritten.
const STALE_GENERATED_HOOK_BODIES = {
  "pre-push": [generatedHookBody("pre-push", { forwardPrePushArgs: false })],
};

/**
 * Resolve whether a directory is a non-bare Git working tree. Git exits zero
 * and prints `false` for a bare repository, so status alone is not sufficient:
 * local pre-commit/pre-push hooks can never run there.
 * @param {string} [cwd] - Directory to inspect.
 * @param {NodeJS.ProcessEnv} [env] - Process environment for the Git probe.
 * @returns {{inside: boolean, bare: boolean}} Working-tree state.
 */
export function gitWorkTreeState(cwd = process.cwd(), env = process.env) {
  const result = run("git", ["rev-parse", "--is-inside-work-tree"], {
    cwd,
    env,
  });
  const value = (result.stdout || "").trim();
  const answered = !result.error && result.status === 0;
  return {
    inside: answered && value === "true",
    bare: answered && value === "false",
  };
}

/**
 * Read core.hooksPath without conflating an absent key with a failed Git
 * command. `git config --get` uses status 1 for a missing value; every other
 * nonzero outcome means the effective hook location is unknown and callers
 * must not claim native hooks are active.
 * @param {string} [cwd] - Repo directory to read config from.
 * @param {NodeJS.ProcessEnv} [env] - Process environment for the Git probe.
 * @returns {{value: string, error: string|null}} Hook-path probe state.
 */
export function hooksPathConfigState(cwd = process.cwd(), env = process.env) {
  const result = run("git", ["config", "--get", "core.hooksPath"], {
    cwd,
    env,
  });
  if (!result.error && result.status === 0) {
    return { value: (result.stdout || "").trim(), error: null };
  }
  if (!result.error && result.status === 1) {
    return { value: "", error: null };
  }
  const detail =
    (result.stderr || "").trim() ||
    result.error?.message ||
    `git config exited with status ${result.status}`;
  return {
    value: "",
    error: `Could not determine core.hooksPath: ${detail}`,
  };
}

/**
 * The configured core.hooksPath value, or "" when unset. When this is set, git
 * ignores .git/hooks entirely, so wiring must account for it.
 * @param {string} [cwd] - Repo directory to read config from.
 * @param {NodeJS.ProcessEnv} [env] - Process environment for the Git probe.
 * @returns {string} Configured value, trimmed, or "".
 */
export function hooksPathConfig(cwd = process.cwd(), env = process.env) {
  return hooksPathConfigState(cwd, env).value;
}

/**
 * Whether a core.hooksPath value is husky-era wiring this tool used before
 * v3 (husky v9 sets `.husky/_`; husky v8 used `.husky`). These are safe to
 * migrate away from automatically; any other value belongs to another hook
 * manager and must be left alone.
 * @param {string} value - core.hooksPath value.
 * @returns {boolean} True for husky-created hooksPath values.
 */
export function isHuskyHooksPath(value) {
  const normalized = String(value ?? "")
    .trim()
    .replace(/\\/g, "/")
    .replace(/\/+$/, "");
  return normalized === ".husky/_" || normalized === ".husky";
}

/**
 * The directory git reads native hooks from, independent of core.hooksPath:
 * `<common dir>/hooks` (linked worktrees share the main repo's hooks).
 * @param {string} [cwd] - Repo directory to resolve from.
 * @param {NodeJS.ProcessEnv} [env] - Process environment for the Git probe.
 * @returns {string|null} Hooks directory path, or null outside a repo.
 */
export function gitHooksDir(cwd = process.cwd(), env = process.env) {
  const result = run("git", ["rev-parse", "--git-common-dir"], { cwd, env });
  if (result.error || result.status !== 0) {
    return null;
  }
  const commonDir = (result.stdout || "").trim();
  if (!commonDir) {
    return null;
  }
  return path.resolve(cwd, commonDir, "hooks");
}

/**
 * Ask Git for the hook directory it will actually use after applying
 * core.hooksPath. Unlike resolving the raw config value in Node, this honors
 * Git's tilde expansion and other path semantics.
 * @param {string} [cwd] - Repo directory to resolve from.
 * @param {NodeJS.ProcessEnv} [env] - Process environment for the Git probe.
 * @returns {string|null} Absolute effective hooks directory, or null on error.
 */
export function effectiveHooksDir(cwd = process.cwd(), env = process.env) {
  const result = run("git", ["rev-parse", "--git-path", "hooks"], {
    cwd,
    env,
  });
  if (result.error || result.status !== 0) {
    return null;
  }
  const hooksDir = (result.stdout || "").trim();
  return hooksDir ? path.resolve(cwd, hooksDir) : null;
}

/**
 * Classify a hook file so repair logic can react appropriately:
 *   missing                → recreate from hookBody
 *   wired                  → our exact generated body; healthy
 *   stale-wired            → exact older generated body; safe to refresh
 *   custom-with-command    → user's own hook that still calls us; healthy
 *   non-executable         → hook contents may be wired, but Git will not run
 *                            the file on POSIX
 *   uninspectable          → the path exists but cannot be safely read as a
 *                            regular hook file
 *   custom-without-command → user's own hook that never calls us; a problem to
 *                            report but never overwrite.
 * @param {string} hooksDir - Directory containing the hook files.
 * @param {string} name - Hook name (e.g. "pre-commit").
 * @param {{requireExecutable?: boolean}} [options] - Whether POSIX mode bits
 *   participate in health classification. Ownership-only callers can disable
 *   this while comparing generated/custom hook contents.
 * @returns {"missing"|"wired"|"stale-wired"|"custom-with-command"|"non-executable"|"uninspectable"|"custom-without-command"} Classification.
 */
export function classifyHook(
  hooksDir,
  name,
  { requireExecutable = true } = {},
) {
  const hookPath = path.join(hooksDir, name);
  let stats;
  let content;
  try {
    // Never follow a hook symlink while deciding whether repair may write to
    // this path. A dangling link looks "missing" through existsSync(), and a
    // link to an older generated body could otherwise make writeHook overwrite
    // a target outside the hooks directory.
    stats = fs.lstatSync(hookPath);
    if (!stats.isFile()) {
      return "uninspectable";
    }
    content = fs.readFileSync(hookPath, "utf8");
  } catch (error) {
    if (error?.code === "ENOENT" || error?.code === "ENOTDIR") {
      return "missing";
    }
    return "uninspectable";
  }

  // Git for Windows executes hooks through its bundled shell without relying
  // on POSIX mode bits. Everywhere else, a present but non-executable file is
  // ignored by Git and must never be reported as active.
  if (
    requireExecutable &&
    process.platform !== "win32" &&
    (stats.mode & 0o111) === 0
  ) {
    return "non-executable";
  }
  if (content === hookBody(name)) {
    return "wired";
  }
  if (STALE_GENERATED_HOOK_BODIES[name]?.includes(content)) {
    return "stale-wired";
  }
  return hasExecutableHookCommand(content, name)
    ? "custom-with-command"
    : "custom-without-command";
}

/**
 * Recognize a deliberately conservative shell invocation. The expected
 * command must begin an executable line (optionally through `command` or
 * `exec`), so comments, echo/printf output, assignments, and quoted examples
 * cannot masquerade as active wiring.
 * @param {string} content - Hook file contents.
 * @param {string} name - Hook name (e.g. "pre-commit").
 * @returns {boolean} Whether an executable line invokes the expected command.
 */
function hasExecutableHookCommand(content, name) {
  const expected = hookCommand(name).replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const invocation = new RegExp(
    `^(?:(?:command|exec)\\s+)?${expected}(?=$|[\\s;&|<>])`,
  );

  let quote = null;
  let continued = false;
  const heredocs = [];

  for (const line of content.split(/\r?\n/)) {
    if (heredocs.length > 0) {
      const current = heredocs[0];
      const candidate = current.stripTabs ? line.replace(/^\t+/, "") : line;
      if (candidate === current.delimiter) {
        heredocs.shift();
      }
      continue;
    }

    // A command-looking line is inert while it is part of a multiline quoted
    // value, a heredoc body, or the continued argument list of the prior line.
    if (quote === null && !continued && invocation.test(line.trimStart())) {
      return true;
    }

    const state = scanShellLine(line, quote);
    quote = state.quote;
    continued = state.continued;
    heredocs.push(...state.heredocs);
  }

  return false;
}

/**
 * Track only the shell lexical state needed to reject inert multiline examples.
 * This is intentionally not a full shell parser: uncertain constructs produce
 * false negatives (manual remediation) rather than false healthy claims.
 * @param {string} line - One hook source line.
 * @param {"'"|'\"'|'`'|null} initialQuote - Quote carried from the prior line.
 * @returns {{quote: "'"|'\"'|'`'|null, continued: boolean, heredocs: Array<{delimiter: string, stripTabs: boolean}>}} State for following lines.
 */
function scanShellLine(line, initialQuote) {
  let quote = initialQuote;
  let continued = false;
  const heredocs = [];

  for (let index = 0; index < line.length; index += 1) {
    const char = line[index];

    if (quote !== null) {
      if (char === quote) {
        quote = null;
      } else if (quote !== "'" && char === "\\") {
        // Backslashes escape the following character in double quotes and
        // legacy backtick substitutions. A final backslash continues the line.
        if (index === line.length - 1) {
          continued = true;
        } else {
          index += 1;
        }
      }
      continue;
    }

    if (char === "#" && isShellWordBoundary(line, index)) {
      break;
    }
    if (char === "'" || char === '"' || char === "`") {
      quote = char;
      continue;
    }
    if (char === "\\") {
      if (index === line.length - 1) {
        continued = true;
      } else {
        index += 1;
      }
      continue;
    }
    if (char === "<" && line[index + 1] === "<" && line[index + 2] !== "<") {
      const parsed = parseHeredocDelimiter(line, index + 2);
      if (parsed.delimiter) {
        heredocs.push({
          delimiter: parsed.delimiter,
          stripTabs: parsed.stripTabs,
        });
      }
      index = parsed.endIndex - 1;
    }
  }

  return { quote, continued, heredocs };
}

/**
 * Whether an unquoted # starts a shell comment rather than continuing a word.
 * @param {string} line - Hook source line.
 * @param {number} index - Index of the # character.
 * @returns {boolean} Whether the remainder of the line is a comment.
 */
function isShellWordBoundary(line, index) {
  return index === 0 || /[\s;&|()]/.test(line[index - 1]);
}

/**
 * Read a simple POSIX heredoc delimiter and apply shell quote removal.
 * @param {string} line - Hook source line.
 * @param {number} startIndex - First character after the << operator.
 * @returns {{delimiter: string, stripTabs: boolean, endIndex: number}} Parsed delimiter.
 */
function parseHeredocDelimiter(line, startIndex) {
  let index = startIndex;
  let stripTabs = false;
  let quote = null;
  let delimiter = "";

  if (line[index] === "-") {
    stripTabs = true;
    index += 1;
  }
  while (line[index] === " " || line[index] === "\t") {
    index += 1;
  }

  for (; index < line.length; index += 1) {
    const char = line[index];
    if (quote !== null) {
      if (char === quote) {
        quote = null;
      } else if (quote !== "'" && char === "\\" && index + 1 < line.length) {
        index += 1;
        delimiter += line[index];
      } else {
        delimiter += char;
      }
      continue;
    }
    if (char === "'" || char === '"') {
      quote = char;
      continue;
    }
    if (char === "\\" && index + 1 < line.length) {
      index += 1;
      delimiter += line[index];
      continue;
    }
    if (/\s|[;&|<>()]/.test(char)) {
      break;
    }
    delimiter += char;
  }

  return { delimiter, stripTabs, endIndex: index };
}

/**
 * Write the generated hook file (creating the hooks dir if needed) and mark it
 * executable. Callers decide when writing is safe; this never checks content.
 * @param {string} hooksDir - Directory to write into.
 * @param {string} name - Hook name (e.g. "pre-commit").
 */
export function writeHook(hooksDir, name) {
  try {
    const directory = fs.lstatSync(hooksDir);
    if (!directory.isDirectory()) {
      throw new Error("The hooks path is not a regular directory");
    }
  } catch (error) {
    if (error?.code !== "ENOENT") {
      throw error;
    }
    fs.mkdirSync(hooksDir, { recursive: true });
  }
  const hookPath = path.join(hooksDir, name);
  fs.writeFileSync(hookPath, hookBody(name));
  fs.chmodSync(hookPath, 0o755);
}

// Exact hook bodies this tool generated into `.husky/` before v3 (2.x ran the
// bin; 1.x ran vendored scripts). Files matching these are OUR artifacts —
// safe to clean up — while anything else in `.husky/` is user-authored.
export const LEGACY_HUSKY_HOOK_BODIES = {
  "pre-commit": [
    "commitment-issues precommit\n",
    "node scripts/precommit-unified.mjs\n",
  ],
  "pre-push": ["commitment-issues prepush\n", "node scripts/prepush.mjs\n"],
};

/**
 * User-authored hook files still sitting in `.husky/` that git no longer runs
 * once core.hooksPath stops pointing there. Our own generated legacy wiring
 * and husky's runtime (`_`, `.gitignore`) are not the user's work, so they are
 * excluded.
 * @param {string} [cwd] - Project root to inspect.
 * @returns {string[]} Repo-relative paths (e.g. ".husky/commit-msg").
 */
export function leftoverHuskyHooks(cwd = process.cwd()) {
  const dir = path.join(cwd, ".husky");
  if (!fs.existsSync(dir)) {
    return [];
  }
  const leftovers = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (!entry.isFile() || entry.name === ".gitignore") {
      continue;
    }
    const ourBodies = LEGACY_HUSKY_HOOK_BODIES[entry.name];
    if (ourBodies) {
      const content = fs.readFileSync(path.join(dir, entry.name), "utf8");
      if (ourBodies.includes(content)) {
        continue;
      }
    }
    leftovers.push(`.husky/${entry.name}`);
  }
  return leftovers;
}

/**
 * The husky-era artifacts this tool generated that {@link removeLegacyHuskyWiring}
 * would delete: exact-match `.husky` hook files plus husky's runtime dir.
 * Exposed separately so a dry run can preview the exact same decision.
 * @param {string} [cwd] - Project root to inspect.
 * @returns {string[]} Repo-relative paths (e.g. ".husky/pre-commit").
 */
export function legacyHuskyWiringPaths(cwd = process.cwd()) {
  const dir = path.join(cwd, ".husky");
  if (!fs.existsSync(dir)) {
    return [];
  }
  const targets = [];
  for (const [name, bodies] of Object.entries(LEGACY_HUSKY_HOOK_BODIES)) {
    const hookPath = path.join(dir, name);
    if (
      fs.existsSync(hookPath) &&
      bodies.includes(fs.readFileSync(hookPath, "utf8"))
    ) {
      targets.push(`.husky/${name}`);
    }
  }
  if (fs.existsSync(path.join(dir, "_"))) {
    targets.push(".husky/_");
  }
  return targets;
}

/**
 * Delete the husky-era wiring this tool created: `.husky` hook files whose
 * bodies exactly match what we generated, husky's runtime dir (`.husky/_`),
 * and the `.husky` dir itself once empty. User-authored files are never
 * touched.
 * @param {string} [cwd] - Project root to clean.
 * @returns {string[]} Repo-relative paths that were removed.
 */
export function removeLegacyHuskyWiring(cwd = process.cwd()) {
  const removed = legacyHuskyWiringPaths(cwd);
  for (const target of removed) {
    fs.rmSync(path.join(cwd, target), { recursive: true, force: true });
  }
  if (removed.length > 0) {
    const dir = path.join(cwd, ".husky");
    const remaining = fs
      .readdirSync(dir)
      .filter((name) => name !== ".gitignore");
    if (remaining.length === 0) {
      fs.rmSync(dir, { recursive: true, force: true });
    }
  }
  return removed;
}
